
spring:
  config:
    activate:
      on-profile: "pro"

build:
  version: "3.0pro"

accounts:
  message: "Welcome to EazyBankProduction accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345